'use strict';

module.exports = {
  HTTP_HOST: '0.0.0.0',
  HTTP_PORT: 10101,
  PROJECT_TITLE: 'Blockchain - Exchange',
  NUMBER_OF_DECIMAL_PLACES: 4,
  MONGODB_HOST: process.env.PAYMENT_MONGODB_HOST || '0.0.0.0',
  MONGODB_PORT: process.env.PAYMENT_MONGODB_PORT || 27017,
  MONGODB_USERNAME: process.env.PAYMENT_MONGODB_USERNAME ?? '',
  MONGODB_PASSWORD: process.env.PAYMENT_MONGODB_PASSWORD ?? '',
  MONGODB_DB_NAME: process.env.PAYMENT_MONGODB_DB_NAME || 'blockchain',
  MEMPOOL_TRANSACTION_STATUS_PENDING: 'PENDING'
};
