'use strict';

module.exports = {
  HTTP_HOST: '0.0.0.0',
  HTTP_PORT: 10102,
  PROJECT_TITLE: 'Blockchain - Miner',
  ROOT_COIN_SOURCE: 'ROOT_COIN_SOURCE',
  BLOCKCHAIN_ROOT_MINER_ADDRESS: 'BLOCKCHAIN_ROOT_MINER_ADDRESS',
  MIN_NONCE: 1,
  MAX_NONCE: 4294967296,
  NUMBER_OF_LEADING_ZEROS: 4,
  NUMBER_OF_DECIMAL_PLACES: 4,
  COIN_HALVING_BLOCK_THRESHOLD: 1024,
  STARTING_COINS_FOR_MINING_PER_BLOCK: 128,
  MAX_TRANSACTIONS_PER_BLOCK: 16,
  MIN_TRANSACTIONS_PER_BLOCK: 1,
  MAX_SIZE_OF_ALL_TRANSACTIONS_PER_BLOCK_IN_BYTES: 16384, // 16KB = 16 * 1024 bytes
  BLOCK_MINING_CRON_TIME: '*/30 * * * * *',
  MONGODB_HOST: process.env.PAYMENT_MONGODB_HOST || '0.0.0.0',
  MONGODB_PORT: process.env.PAYMENT_MONGODB_PORT || 27017,
  MONGODB_USERNAME: process.env.PAYMENT_MONGODB_USERNAME ?? '',
  MONGODB_PASSWORD: process.env.PAYMENT_MONGODB_PASSWORD ?? '',
  MONGODB_DB_NAME: process.env.PAYMENT_MONGODB_DB_NAME || 'blockchain',
  TRANSACTION_TYPE_REWARD_COIN: 'REWARD_COIN_TRANSACTION',
  TRANSACTION_TYPE_FEE_COIN: 'FEE_COIN_TRANSACTION',
  TRANSACTION_TYPE_COIN: 'COIN_TRANSACTION',
  MEMPOOL_TRANSACTION_STATUS_MINED: 'MINED',
  MEMPOOL_TRANSACTION_STATUS_PENDING: 'PENDING'
};
